### PR TITLE
[CSL 150] improve android documentation

### PR DESCRIPTION
**Pull request by crgee1**
- Build gradle
- Run gradle task
Screen Shot 2021-07-13 at 10 58 42 AM

- in terminal: `open library/docs/library/index.html `

### CODE REVIEW

**Comment by rubikzube** [comment]
Hmm @crgee1 ... Let's discuss tomorrow as something doesn't look quite right here to me ... maybe I'm doing something wrong

**Review by rubikzube — CHANGES_REQUESTED** [review]
Can we suppress  `io.constructor.data.model.conversion` and `io.constructor.data.model.purchase` also?



io.constructor.data.model.conversion |  
-- | --
io.constructor.data.model.purchase

**Review by rubikzube — CHANGES_REQUESTED** [review]
I'm still seeing a bunch of extraneous documentation files ... can we remove all of the HTML and regenerate?

**Comment by crgee1** [comment]
> I'm still seeing a bunch of extraneous documentation files ... can we remove all of the HTML and regenerate?

I reran the docs, what extraneous docs are you seeing?

**Pull request merged**
